import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import { copyFileSync, existsSync, mkdirSync, readFileSync } from 'fs';
import path from 'path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;
const prod = process.argv[2] === 'production';

const readPluginIdFromManifest = () => {
	const manifestPath = path.join(process.cwd(), 'manifest.json');
	if (!existsSync(manifestPath)) {
		throw new Error(`manifest.json not found at ${manifestPath}`);
	}

	const raw = readFileSync(manifestPath, 'utf-8');
	let parsed;
	try {
		parsed = JSON.parse(raw);
	} catch (e) {
		throw new Error(`manifest.json is not valid JSON: ${e.message}`);
	}

	const id = parsed?.id;
	if (typeof id !== 'string' || !id.trim()) {
		throw new Error(`manifest.json is missing a valid "id" field`);
	}
	return id.trim();
};

const getDevVaultPath = () => {
	let devVaultPath = '';
	if (existsSync('.env.local')) {
		// in env.local
		const content = readFileSync('.env.local', 'utf-8');
		const match = content.match(/^OBSIDIAN_VAULT_PATH=(.+)$/m);
		devVaultPath = match ? match[1].trim() : '';
	} else {
		// in .env
		devVaultPath = (process.env.OBSIDIAN_VAULT_PATH || '').trim();
	}
	devVaultPath = devVaultPath
		.replace(/^"(.*)"$/, '$1')
		.replace(/^'(.*)'$/, '$1'); // strip quotes
	return devVaultPath;
};

// Automatically copy into obsidian vault on changes (for dev buil) from environment variable
function copyToVaultPlugin() {
	return {
		name: 'copy-to-vault',
		setup(build) {
			const pluginId = readPluginIdFromManifest();
			const vaultPath = getDevVaultPath();

			build.onEnd((result) => {
				if (result.errors.length > 0) {
					return;
				}

				if (!vaultPath) {
					console.warn('OBSIDIAN_VAULT_PATH not set; skipping copy.');
					return;
				}
				if (!existsSync(vaultPath)) {
					console.warn(
						`Vault path does not exist; skipping copy: ${vaultPath}`,
					);
					return;
				}

				const pluginDir = path.join(
					vaultPath,
					'.obsidian',
					'plugins',
					pluginId,
				);
				mkdirSync(pluginDir, { recursive: true });

				const filesToCopy = ['main.js', 'styles.css', 'manifest.json'];
				for (const file of filesToCopy) {
					const src = path.join(process.cwd(), file); // keep your output layout
					const dest = path.join(pluginDir, file);

					if (existsSync(src)) {
						copyFileSync(src, dest);
					} else {
						console.warn(`Could not find ${src}; skipping copy`);
					}
				}

				console.log(`Copied output to ${pluginDir}`);
			});
		},
	};
}

const plugins = !prod ? [copyToVaultPlugin()] : [];
const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins,
	],
	format: 'cjs',
	target: 'es2018',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	plugins,
});

if (prod) {
	await context.rebuild();
	await context.dispose();
} else {
	await context.watch();
}
